var DB_FOOD = [
  "https://www.foodnetwork.com/",
  "https://www.yummly.com/",
  "https://www.epicurious.com/",
  "https://www.bonappetit.com/",
  "https://www.food.com/",
  "https://www.cookstr.com/",
  "https://www.food52.com/",
  "https://www.thekitchn.com/",
  "https://www.buzzfeedfood.com/",
  "https://www.refinery29.com/food",
  "https://www.cosmopolitan.com/food-drink",
  "https://www.womansday.com/food",
  "https://www.redbookmag.com/food",
  "https://www.delicious.com.au/",
  "https://www.ina Garten.com/recipes",
  "https://www.cookingchanneltv.com/recipes",
  "https://www.hgtv.com/recipes",
  "https://www.travelchannel.com/food",
  "https://www.foodnetwork.ca/recipes",
  "https://www.foodnetwork.co.uk/recipes",
];
