var DB_MOVIES = [
  "https://www.metacritic.com/",
  "https://www.hbo.com/",
  "https://www.crave.ca/",
  "https://www.criterionchannel.com/",
  "https://www.sundance.tv/",
  "https://www.hoopladigital.com/",
  "https://www.vudu.com/",
  "https://www.fandangonow.com/",
  "https://www.cinemarktheatres.com/",
  "https://www.everyman.com/",
  "https://www.ifccenter.com/",
  "https://www.empireonline.com/movies",
  "https://www.denofgeek.com/movies",
  "https://www.vulture.com/movies",
  "https://www.avclub.com/movies",
];
