var DB_MUSIC = [
  "https://www.pandora.com/",
  "https://www.iheart.com/",
  "https://www.napster.com/",
  "https://www.pitchfork.com/",
  "https://www.consequence.net/",
  "https://www.stereogum.com/",
  "https://www.musicbrainz.org/",
  "https://www.eventbrite.com/",
  "https://www.ticketfly.com/",
  "https://www.vevo.com/",
  "https://www.azlyrics.com/",
  "https://www.lyricsmode.com/",
  "https://www.musictech.net/",
];
