var DB_STREAMING = [
  "https://www.criterionchannel.com/",
  "https://www.sundance.tv/",
  "https://www.ifcfilms.com/",
  "https://www.magellantv.com/",
  "https://www.historyvault.com/",
  "https://www.acorntv.com/",
  "https://www.hoopladigital.com/",
  "https://www.hoopla.us/",
  "https://www.dailymotion.com/",
  "https://www.mixcloud.com/",
  "https://www.pandora.com/",
  "https://www.iheart.com/",
  "https://www.napster.com/",
];
